//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailerDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailReceiver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailReceiver()
        {
            this.EmailQueues = new HashSet<EmailQueue>();
        }
    
        public long EmailReceiverId { get; set; }
        public byte EmailAddresType { get; set; }
        public string EmailAddress { get; set; }
        public string ToPerson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailQueue> EmailQueues { get; set; }
    }
}
